/* Minimal config.h for the WASM build; the impls #include it but use no
 * macros from it (real DVB constants live in include/dvbs2rx/dvb_config.h).
 * Normally generated by gr-dvbs2rx's own CMake. */
#ifndef GR_DVBS2RX_WASM_CONFIG_H
#define GR_DVBS2RX_WASM_CONFIG_H
#endif
